### ISSUE TITLE
Example: Interactive Ethereum roadmap as a website

### ISSUE THREAD

**Issue by Vid201** [2077-Collective/better-2077#13]
## User story

As an Ethereum community member (or newcomer), I want to follow the roadmap and progress of Ethereum so I can be up-to-date with the latest developments.

## Solution

Create a dynamic website that builds upon the image that Vitalik created for the Ethereum roadmap. Users can click on the blocks of the roadmap and see more information about that roadmap's part - e.g., which EIPs are part of this, which high-level construct this block is part of, is an execution or consensus upgrade, does this helps rollups or Ethereum core protocol...

## How does it benefit the Ethereum ecosystem?

The website offers the Ethereum ecosystem a visual and interactive website with a roadmap where they can track the progress. The website can also be more quickly updated when new things are released. It's also more discoverable than the current screenshots/images of the roadmap image.

### Why does this not exist yet?

There was no one that would take up this challenge.

## Tasks

- [ ] Create a list of Ethereum roadmap topics and group them together according to the "block" on the roadmap image
- [ ] Develop the interactive website
- [ ] Share and promote the website

## Notes

Link to the Ethereum roadmap image created by Vitalik: https://pbs.twimg.com/media/FgwVhUjaAAEx_Bb.jpg:large
